#server:
#  port: 8080
#spring:
#  redis:
#    SerializerType: JDK
#    needMultiton:
#    client-type: jedis
#    host: 192.168.219.120
#    password:
#    connectTimeout: 2000
#    timeout: 2000
#    port: 6379
#    sentinel:
#      master: mymaster
#      password: sssss
#      nodes: 127.0.0.1:26379,127.0.0.1:36379
#    #cluster:
#    #  nodes: 127.0.0.2:26379,127.0.0.2:36379
#    #  max-redirects: 3
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: 3000
#        min-idle: 2
#    reddison:
#      mode: single
#      enableLock: true
#      pool:
#        max-active: 4
#        max-wait: 3000
#        min-idle: 0
#nc:
#  okhttp:
#    connectTimeOut: 8
#    readTimeOut: 5
#    writeTimeOut: 3
#  thread:
#    pool:
#      corePoolSize: 2
#      maximumPoolSize: 2
#      keepAliveTime: 3
#      capacity: 5